-- AutoElétrica 13.6.187 — infraestrutura administrativa de perfis normativos
alter table if exists public.usuarios add column if not exists role text not null default 'USUARIO';

create table if not exists public.perfis_normativos (
  id bigint generated by default as identity primary key,
  concessionaria text not null,
  uf text not null,
  municipio text not null default '',
  documento text not null default '',
  revisao text not null default '',
  vigencia text not null default '',
  fonte_oficial text not null default '',
  regras jsonb not null default '{}'::jsonb,
  status text not null default 'RASCUNHO' check (status in ('RASCUNHO','VALIDADO','ATIVO','INATIVO')),
  criado_por text not null default '',
  validado_por text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_perfis_normativos_publicados on public.perfis_normativos(status,uf,municipio,concessionaria);
-- Defina o administrador uma única vez no SQL Editor, substituindo o e-mail abaixo:
-- update public.usuarios set role='ADMIN' where lower(email)=lower('SEU_EMAIL_ADMIN@DOMINIO.COM');
-- Alternativamente, configure no secrets.toml: [admin] emails=["email@dominio.com"]
